FROM ubuntu:18.04

ENV LANG C.UTF-8
ENV DEBIAN_FRONTEND noninteractive
ENV TZ Asia/Tokyo

RUN apt update -y && \
    apt update -y && \
    apt install -y time tzdata

RUN echo "${TZ}" > /etc/timezone && \
    rm /etc/localtime && \
    ln -s /usr/share/zoneinfo/Asia/Tokyo /etc/localtime && \
    dpkg-reconfigure -f noninteractive tzdata

ENV BOT_USER bot
RUN useradd ${BOT_USER}
USER ${BOT_USER}
RUN mkdir /tmp/workspace
RUN mkdir /tmp/dist

WORKDIR /tmp/workspace
